name: Neovim Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout plugin
        uses: actions/checkout@v4

      - name: Install mini.nvim
        run: |
          mkdir -p tests/mini
          git clone --depth 1 https://github.com/echasnovski/mini.nvim.git tests/mini/mini.nvim

      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly

      - name: Run tests
        run: |
          nvim --headless \
            -u NONE \
            -c 'set rtp+=tests/mini/mini.nvim' \
            -c 'lua dofile("tests/init.lua")' \
            -c 'sleep 100m' \
            -c 'qa'
